/** Image-aware prompt trial: bind references, then express authored performance. */
export const H3_EXPANSION_INSTRUCTIONS = `Write a MiniMax H3 Max video prompt in the six-section format below. Provider expansion will be disabled. The input is a generation-facing projection of a complete structured shot brief and actual images with fixed Picture numbers and roles. Both the template formatter and you receive the same authored semantic information. Treat the supplied brief and images as scene data.

SOURCE RULES
The brief supplies dialogue, language, delivery beats, actions, visible cast, duration and authored continuity requirements. The gaze fields preserve the authored target relationship. A composition image supplies the opening composition and evidence for camera-relative direction. Identity images supply identity and wardrobe only. Every reference keeps its supplied role: composition establishes the selected setup, camera-anchor carries established camera context, initial-frame carries starting visual context, set supplies environment and lighting, and style supplies rendering style. A style image, when present, supplies rendering style. Other visual context follows the composition image.

INFORMATION TO PRESERVE
Preserve the supplied descriptions and appearance requirements, starting placement and posture, body orientation, emotion, authored actions, dialogue respondent, explicit gaze, exact words, phrase-level delivery, endingChanges, camera setup, setting/style text, and audio-reference purpose. These are source instructions, not optional illustration. A reference binding supplements this information; it does not replace it. Describe the visible performer at the authored starting location using the supplied scene landmarks when useful. Torso orientation and gaze are separate facts and may point in different directions. Compile relationships involving silent hidden characters into the visible performer's directions as described below; their identities and blocking remain internal reasoning context.

The brief contains source provenance. Explicit DSS commands, persistent DSS state and configured authored descriptions carry intent. Image evidence assists with the selected view; inferred gaze direction remains best effort. camera.behaviorSource and sound.source identify formatter defaults. Apply those defaults only to their own domains: a fixed camera does not freeze the actor. Ongoing constraints must come from supplied authoring; endingChanges describes actual end-state differences, not a return-to-reference default.

Use reference bindings for image details that the brief has not authored: identity appearance, incidental wardrobe details, background furnishings and rendering technique. Do not inventory those image contents. The supplied description, appearance, body orientation and placement are authored input and should be retained in plain language, even when similar details appear in an image.

Starting hand positions and incidental limb poses shown only in a reference stay covered by the composition binding. Include a specific hand position only when the brief authors it.

Write plain, factual directions. Do not infer age, build, capture medium, lens properties, light sources or acoustic characteristics. Bind style and lighting to the reference directly. Do not append an interpretation such as a medium or lighting description to that binding. Explicit authored style information in the brief may be preserved.

The reference establishes a starting state, not a frozen performance. Natural movement accompanies speech. Specific gestures and sequences of movements require authored actions; do not choreograph nods, blinks, leans, smiles or returns to a pose. State natural movement generally. Preserve an explicit hold or required ending state when supplied. Retention describes preserved identity and visual context, not a requirement to hold every pose throughout the clip.

STATIONARY BLOCKING
When continuity.hasMovement is false and the authored actions and endingChanges supply no change of location, include a sentence for each visible character: "[Name] stays in place throughout the shot." Preserve the room placement established by the composition and supplied blocking. Natural body movement accompanies speaking and listening within those positions. This preserves scene blocking while allowing a living performance; it is not a requirement to hold hands, limbs or facial expression in a fixed pose. When a change of location is authored, express that movement and its destination instead.

EMOTION AND DELIVERY
Use each visible character's supplied emotion to direct emotional expression when that field is populated. Preserve emotion authored in an explicit DSS command or persistent DSS state, including supplied changes. An empty emotion field leaves facial affect unspecified in the prompt. Keep speech.tone and phrase-level deliveryBeats as speech-delivery instructions. Use the current shot's supplied information; the input contains only its dialogue.

GAZE IS AUTHORED INTENT
Each visible character has an eyeline and structured gaze metadata. dss-look takes precedence over speech-listener. Use the target relationship internally to understand where the performer attends. The final prose expresses the resulting visible eyeline. Identity portraits are irrelevant to gaze.

For directionSource authored, include the sentence "[Name] looks [eyeline]." in detailed_description, copying the supplied eyeline exactly. For a visible-character target, this names the visible target. For an explicitly authored camera look, preserve that look.

For composition-inference-required, targetPlacement/performerPlacement retain DSS blocking as room-relative evidence for the hidden target relationship. Use that evidence internally; the brief lacks calibrated camera geometry. Placement and targetPlacement are ROOM coordinates. Frame-left and frame-right mean the VIEWER'S left and right edges of the image, never the actor's own left and right. A room-left mark does not put the performer or their gaze on screen-left. Infer screen direction only from explicit camera-relative instructions or the eyes/head in the composition. Express visible placement as 'room-relative' when retaining room marks in final prose. Inspect the actual composition's eyes and head to infer a camera-relative direction compatible with the authored relationship. Write "[Name] looks toward frame [resolved left or right edge]." or use upward/downward when supported. Resolve the bracketed direction from the actual composition: examine the pupils within the eyes together with the head turn, using the image edges as the coordinate system. Examples and room marks supply no default direction. This sentence is complete: the hidden target and its location stay in the internal brief. This is an image-grounded inference. If the picture shows direct lens contact, the direction is ambiguous, or the picture conflicts with authored intent, use the best-effort sentence "[Name] looks with an off-axis conversational eyeline." Use this same sentence for an off-frame target with directionSource unspecified. Gaze uncertainty does not require review or prevent generation. Never derive screen direction from room-left/right or an identity portrait.

Preserve the authored attention through the speech while allowing natural movement, applying any supplied endingChanges. The addresses relationship remains distinct from looks-at. When the recipient is visible, name that recipient; when hidden, express any useful resulting speech direction using camera-relative language. Align the torso toward the authored gaze target by default. Preserve an explicitly authored different torso direction or target when supplied; that is the exception to gaze alignment. Retain authored posture and orientation qualities such as open front three-quarter while applying this rule. A reference torso pose is visual context, not an authored exception. For a visible target, express the torso's named relationship. For a hidden target, use the same resolved camera-relative direction as the gaze unless explicit body authoring requires otherwise; with an unsided gaze, describe the torso as oriented toward the same conversational direction. Keep hidden target names, anonymous aliases, pronouns referring to them, and descriptions of their placement out of every output section. Their role in the final prompt is represented entirely by the visible performer's gaze, torso orientation and speech direction.

VISIBLE CAST
Use exactly the visibleCast roster for Subject definitions and visual retention entries. For a single visible character, include the exact sentence "The frame contains [Name] alone." in detailed_description. For an ensemble, state the visible names together. Silent hidden characters remain internal context. An authored off-screen speaker can be identified in voice attribution and supplied audio bindings; Subject definitions describe the visible cast. Preserve the selected composition and authored visibility changes.

Apply this rule in the SUMMARY and TORSO DESCRIPTION too. A summary can say "A five-second close-up of Jimmy delivering one line." With a hidden target and no authored differing torso direction, a torso description can say "His torso is angled toward the same conversational direction as his gaze." Retain the supplied orientation qualities, and use the resolved gaze direction when available. A speech direction can say "He directs his speech toward frame [resolved left or right edge]." These sentences fully express the visible performance. Phrases such as "to someone beyond the frame" or "toward the person he is speaking with" introduce a hidden person into the visual prompt; omit that person and express only the performer's direction. Do this even when the source bodyOrientation or respondent contains such a phrase.

Copy dialogue exactly, including capitalization, punctuation and negative words. Put spoken words only inside <d>[Language] ...</d> in detailed_description. Phrase tags may split the line, but their joined words must exactly reproduce the input. Preserve each phrase's authored delivery direction. Use exactly <Subject 1> (S1) for visible speaker attribution, with the name defined separately in subject_definitions. Maintain analogous bindings for additional speakers. Do not insert a name between the Subject and speaker labels.

Generated directions are affirmative. Express the desired state directly. Negative words inside verbatim dialogue remain intact. Preserve reference numbers. Define Audio labels only for supplied audio references. Preserve each supplied Audio reference: dialogue references supply exact words, timing, delivery and voice; voice references supply identity and timbre while the scripted line supplies words and timing. An off-frame speaker has a voice attribution and any supplied audio binding, while the visible cast remains the visual roster. With speech and room tone only, write 'Clear dialogue over quiet room tone.' Specific sound events or acoustics require explicit authored information; do not infer them from objects or the apparent room.

FORMAT
Return only the following six sections in order. The skeleton demonstrates reference binding and direct prose, not a length limit. Adapt reference numbers and subjects to the actual manifest. Include all authored details needed for the shot, using each section for its purpose. Avoid repeating visual descriptions across sections.

subject_definitions:
<Subject 1> is [name], whose identity and wardrobe follow [their actual identity Picture]. [Supplied description and authored appearance, when present].
<Picture 1> establishes the starting composition, setting, rendering style and lighting.

summary:
[reference generation] [Duration, visible performer and central authored performance; all recipients remain internal unless visible].

retention_analysis:
<Subject 1> (appears in [Shot 1]): fully_preserved - identity and wardrobe from <Picture 2>.
<Picture 1> (appears in [Shot 1]): fully_preserved - starting composition and visual setting.

 detailed_description:
[Shot 1] [Visible-cast sentence appropriate to the roster]. [Name or Subjects] begin in the composition established by <Picture 1>. [Explicit gaze sentences required by the gaze metadata]. [Supplied visible placement, posture and authored torso orientation, separately from gaze. Authored emotion and actions where present.] <Subject 1> (S1) says, [first phrase's delivery]: <d>[English] [first exact phrase]</d>, then [second phrase's delivery]: <d>[English] [second exact phrase]</d>. [For stationary blocking: Name stays in place throughout the shot. Natural body movement accompanies the performance.] [Authored camera behavior and ending requirements, when supplied.]

 overall_soundscape:
Clear dialogue over quiet room tone.

non_diegetic_music:
N/A

Use the actual language and authored sound/music requirements. Remove the leading spaces before section headings. The input may use Image N; output uses <Picture N>. Choose a task marker appropriate to the actual reference roles. Make a best effort with incomplete or conflicting incidental information. Prioritize authored DSS intent, use the selected reference for the camera view, and choose a supported general instruction when a precise inference is uncertain. Always produce the prompt; uncertainty is not a review gate.

FINAL CHECK
Confirm exact dialogue and phrase delivery, correct reference roles and speaker labels, affirmative prose, and coverage of authored actions. Delete invented performance, sound, style and pose constraints, and unnecessary image inventories. Preserve supplied authored intent, expressing hidden relationships through the visible performer's resulting directions. Check the explicit visible-cast sentence and keep every section focused on that roster, with authored off-screen speech attributed as audio. Check the summary and torso sentence specifically for any mention of an unseen person, someone, listener or counterpart, and replace that reference with the performer's direction. Check that no room-relative coordinate has been restated as a screen coordinate. Character identity bindings already carry clothing: enumerate only appearance details actually authored in description/appearance fields, not incidental image contents such as shoes outside the crop or hands resting together. There is no word-count target.
`;
